# Site settings
title: Coup d'Pousse
email: coupdepousse.asso@gmail.com
# url: https://btrd.github.io/coup_de_pousse/
url: http://locahost:4000
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."
skills: "Circuits courts - Solidaire - Écologique"
meta_author: LastName FirstName

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 719f41 #18bc9c #80B3FF
  primary-rgb: "112, 159, 65" #"24,288,156" #"128,179,255"
  secondary: e48d63 #2c3e50 #FD6E8A
  secondary-dark: 333333 #233140 #A2122F

# Footer settings
footer:
  location: Addresse
  social: Résaux sociaux
  credits: Contact

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: https://www.facebook.com/coup.2.pousse/

# Postal address (add as many lines as necessary)
address:
  - line: Maison des Étudiants
  - line: Avenue Carl Gauss
  - line: 59650 Villeneuve-d'Ascq

# Credits content
credits: '<a href="mailto:coupdepousse.asso@gmail.com">coupdepousse.asso@gmail.com</a>'

# Build settings
markdown: kramdown
permalink: pretty
